/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GerenciaEquipeCirurgica;
import dao.AcomodacaoDao;
import dao.EquipeCirurgicaDao;
import dao.FuncionarioDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Acomodacao;
import model.Prontuario;

/**
 *
 * @author Wanderson_M
 */
public class Cirurgia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cirurgia
     */
    GerenciaEquipeCirurgica gec;
    protected ArrayList<model.EquipeCirurgica> ecs;
    FuncionarioDao fd;
    EquipeCirurgicaDao ecd;
    Consulta consulta;
    ArrayList<Acomodacao> acomodacaoS;
    AcomodacaoDao acomodacaoDao;

    public Cirurgia() {
        initComponents();
        ecd = new EquipeCirurgicaDao();
        gec = new GerenciaEquipeCirurgica();
        fd = new FuncionarioDao();
        acomodacaoDao = new AcomodacaoDao();
        acomodacaoS = new ArrayList();
        preencheCampos();
    }

    public Cirurgia(Consulta consulta) {
        initComponents();
        this.consulta = consulta;
        ecd = new EquipeCirurgicaDao();
        gec = new GerenciaEquipeCirurgica();
        fd = new FuncionarioDao();
        acomodacaoDao = new AcomodacaoDao();

        acomodacaoS = acomodacaoDao.listar("Sala de cirurgia");

        preencheCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        tpCirurgia = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnProximo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jlCirculante = new javax.swing.JLabel();
        jlAnestesista = new javax.swing.JLabel();
        jlInstrumentador = new javax.swing.JLabel();
        ljCirurgiaoPrincipal = new javax.swing.JLabel();
        ljEnfermeiroChefe = new javax.swing.JLabel();
        jlCirurgiaoAssistente = new javax.swing.JLabel();
        tfCirculante = new javax.swing.JTextField();
        tfAnestesista = new javax.swing.JTextField();
        tfInstrumentador = new javax.swing.JTextField();
        tfEnfermeiroChefe = new javax.swing.JTextField();
        tfCirurgiaoPrincipal = new javax.swing.JTextField();
        tfCirurgiaoAssistente = new javax.swing.JTextField();
        cbxFuncionarios = new javax.swing.JComboBox<>();
        btnAnterior = new javax.swing.JButton();
        btnAvancar1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jlData = new javax.swing.JLabel();
        jdcData = new com.toedter.calendar.JDateChooser();
        jsHora = new javax.swing.JSpinner();
        jsMinuto = new javax.swing.JSpinner();
        jlHorario = new javax.swing.JLabel();
        btnVoltar1 = new javax.swing.JButton();
        btnProximo2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jpSalaCirurgia = new javax.swing.JPanel();
        cbxSalaCirurgica = new javax.swing.JComboBox<>();
        btnAnterior1 = new javax.swing.JButton();
        btnAvancar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar2 = new javax.swing.JButton();
        btnProximo3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jpValorRelatorio = new javax.swing.JPanel();
        jlValor = new javax.swing.JLabel();
        ftfValor = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRelatorio = new javax.swing.JTextArea();
        jlRelatorio = new javax.swing.JLabel();
        btnVoltar3 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        jlCirculante.setText("Circulante");

        jlAnestesista.setText("Anestesista");

        jlInstrumentador.setText("Instrumentador");

        ljCirurgiaoPrincipal.setText("Cirurgiao principal");

        ljEnfermeiroChefe.setText("Enfermeiro chefe");

        jlCirurgiaoAssistente.setText("Cirurgiao Assistente");

        tfCirculante.setEditable(false);

        tfAnestesista.setEditable(false);

        tfInstrumentador.setEditable(false);

        tfEnfermeiroChefe.setEditable(false);

        tfCirurgiaoPrincipal.setEditable(false);

        tfCirurgiaoAssistente.setEditable(false);
        tfCirurgiaoAssistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCirurgiaoAssistenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCirculante)
                    .addComponent(jlAnestesista)
                    .addComponent(jlInstrumentador)
                    .addComponent(ljEnfermeiroChefe)
                    .addComponent(ljCirurgiaoPrincipal)
                    .addComponent(jlCirurgiaoAssistente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCirurgiaoAssistente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(tfCirurgiaoPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfEnfermeiroChefe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfInstrumentador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAnestesista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfCirculante, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCirculante)
                    .addComponent(tfCirculante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAnestesista)
                    .addComponent(tfAnestesista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlInstrumentador)
                    .addComponent(tfInstrumentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ljEnfermeiroChefe)
                    .addComponent(tfEnfermeiroChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ljCirurgiaoPrincipal)
                    .addComponent(tfCirurgiaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCirurgiaoAssistente)
                    .addComponent(tfCirurgiaoAssistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbxFuncionarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxFuncionariosItemStateChanged(evt);
            }
        });

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnAvancar1.setText(">>");
        btnAvancar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAvancar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnProximo)
                        .addGap(165, 165, 165))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvancar1)
                    .addComponent(btnAnterior)
                    .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProximo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpCirurgia.addTab("Equipe Cirurgica", jPanel1);

        jlData.setText("Data");

        jlHorario.setText("Horário");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsHora)
                    .addComponent(jlHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlData)
                    .addComponent(jlHorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jsHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jsMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnVoltar1.setText("Voltar");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        btnProximo2.setText("Próximo");
        btnProximo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnVoltar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProximo2))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar1)
                    .addComponent(btnProximo2))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        tpCirurgia.addTab("Data", jPanel6);

        cbxSalaCirurgica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSalaCirurgicaItemStateChanged(evt);
            }
        });

        btnAnterior1.setText("<<");
        btnAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior1ActionPerformed(evt);
            }
        });

        btnAvancar2.setText(">>");
        btnAvancar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancar2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione a sala cirurgica");

        javax.swing.GroupLayout jpSalaCirurgiaLayout = new javax.swing.GroupLayout(jpSalaCirurgia);
        jpSalaCirurgia.setLayout(jpSalaCirurgiaLayout);
        jpSalaCirurgiaLayout.setHorizontalGroup(
            jpSalaCirurgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSalaCirurgiaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpSalaCirurgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSalaCirurgiaLayout.createSequentialGroup()
                        .addComponent(cbxSalaCirurgica, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvancar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jpSalaCirurgiaLayout.setVerticalGroup(
            jpSalaCirurgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSalaCirurgiaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jpSalaCirurgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSalaCirurgica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior1)
                    .addComponent(btnAvancar2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnVoltar2.setText("Voltar");
        btnVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar2ActionPerformed(evt);
            }
        });

        btnProximo3.setText("Próximo");
        btnProximo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jpSalaCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnVoltar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProximo3)
                .addGap(102, 102, 102))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jpSalaCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo3)
                    .addComponent(btnVoltar2))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        tpCirurgia.addTab("Sala Cirurgica", jPanel8);

        jlValor.setText("Valor");

        taRelatorio.setColumns(20);
        taRelatorio.setRows(5);
        jScrollPane1.setViewportView(taRelatorio);

        jlRelatorio.setText("Relatório");

        javax.swing.GroupLayout jpValorRelatorioLayout = new javax.swing.GroupLayout(jpValorRelatorio);
        jpValorRelatorio.setLayout(jpValorRelatorioLayout);
        jpValorRelatorioLayout.setHorizontalGroup(
            jpValorRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValorRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpValorRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlValor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRelatorio)
                    .addComponent(ftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpValorRelatorioLayout.setVerticalGroup(
            jpValorRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValorRelatorioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnVoltar3.setText("Voltar");
        btnVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar3ActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpValorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnVoltar3)
                        .addGap(88, 88, 88)
                        .addComponent(btnSalvar)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpValorRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar3)
                    .addComponent(btnSalvar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tpCirurgia.addTab("Valor e Relatório", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpCirurgia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCirurgiaoAssistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCirurgiaoAssistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCirurgiaoAssistenteActionPerformed

    private void btnAvancar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancar1ActionPerformed

        if (cbxFuncionarios.getItemCount() != 0) {

            if (cbxFuncionarios.getSelectedIndex() + 1 >= cbxFuncionarios.getItemCount()) {
                cbxFuncionarios.setSelectedIndex(0);
            } else {

                cbxFuncionarios.setSelectedIndex(cbxFuncionarios.getSelectedIndex() + 1);
            }
        }
    }//GEN-LAST:event_btnAvancar1ActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (cbxFuncionarios.getItemCount() != 0) {

            if (cbxFuncionarios.getSelectedIndex() - 1 < 0) {
                cbxFuncionarios.setSelectedIndex(cbxFuncionarios.getItemCount() - 1);
            } else {

                cbxFuncionarios.setSelectedIndex(cbxFuncionarios.getSelectedIndex() - 1);
            }
    }//GEN-LAST:event_btnAnteriorActionPerformed
    }

    private void cbxFuncionariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxFuncionariosItemStateChanged

        Campos(cbxFuncionarios.getSelectedIndex());
    }//GEN-LAST:event_cbxFuncionariosItemStateChanged

    private void cbxSalaCirurgicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSalaCirurgicaItemStateChanged

        Campos(cbxSalaCirurgica.getSelectedIndex());
    }//GEN-LAST:event_cbxSalaCirurgicaItemStateChanged

    private void btnAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior1ActionPerformed
        if (cbxSalaCirurgica.getItemCount() != 0) {

            if (cbxSalaCirurgica.getSelectedIndex() - 1 < 0) {
                cbxSalaCirurgica.setSelectedIndex(cbxSalaCirurgica.getItemCount() - 1);
            } else {

                cbxSalaCirurgica.setSelectedIndex(cbxSalaCirurgica.getSelectedIndex() - 1);
            }
    }//GEN-LAST:event_btnAnterior1ActionPerformed

    }
    private void btnAvancar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancar2ActionPerformed

        if (cbxSalaCirurgica.getItemCount() != 0) {

            if (cbxSalaCirurgica.getSelectedIndex() + 1 >= cbxSalaCirurgica.getItemCount()) {
                cbxSalaCirurgica.setSelectedIndex(0);
            } else {

                cbxSalaCirurgica.setSelectedIndex(cbxSalaCirurgica.getSelectedIndex() + 1);
            }
        }
    }//GEN-LAST:event_btnAvancar2ActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        tpCirurgia.setSelectedIndex(1);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        tpCirurgia.setSelectedIndex(0);
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnProximo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo2ActionPerformed
        tpCirurgia.setSelectedIndex(2);
    }//GEN-LAST:event_btnProximo2ActionPerformed

    private void btnVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar2ActionPerformed
        tpCirurgia.setSelectedIndex(1);
    }//GEN-LAST:event_btnVoltar2ActionPerformed

    private void btnProximo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo3ActionPerformed
        tpCirurgia.setSelectedIndex(3);
    }//GEN-LAST:event_btnProximo3ActionPerformed

    private void btnVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar3ActionPerformed
        tpCirurgia.setSelectedIndex(2);
    }//GEN-LAST:event_btnVoltar3ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed


    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        if (!consulta.isClosed()) {
            consulta.getTpConsulta().setSelectedIndex(3);
        }    }//GEN-LAST:event_formInternalFrameClosing

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        model.Cirurgia cirurgia = new model.Cirurgia();


    }//GEN-LAST:event_btnSalvarActionPerformed

    public void preencheCampos() {
        ecs = ecd.listarE();
        acomodacaoS = acomodacaoDao.listar("Sala de cirurgia");
        if (ecs == null || ecs.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum funcionario cadastrado!");
            btnProximo.setEnabled(false);
        } else {
            for (int i = 0; i < ecs.size(); i++) {
                cbxFuncionarios.addItem("Equipe " + (i + 1));

            }

        }

        for (int i = 0; i < acomodacaoS.size(); i++) {
            cbxSalaCirurgica.addItem(acomodacaoS.get(i).getTipo() + " " + acomodacaoS.get(i).getNumero());
        }

    }

    public void Campos(int i) {

        {

            model.EquipeCirurgica equipeCirurgica = ecs.get(cbxFuncionarios.getSelectedIndex());
            tfAnestesista.setText(equipeCirurgica.getAnestesista().getNome() + " " + equipeCirurgica.getAnestesista().getSobrenome());

            tfCirculante.setText(equipeCirurgica.getCirculante().getNome() + " " + equipeCirurgica.getCirculante().getSobrenome());

            tfCirurgiaoAssistente.setText(equipeCirurgica.getCirurgiaoAssistente().getNome() + " " + equipeCirurgica.getCirurgiaoAssistente().getSobrenome());
            tfCirurgiaoPrincipal.setText(equipeCirurgica.getCirurgiaoPrincipal().getNome() + " " + equipeCirurgica.getCirurgiaoPrincipal().getSobrenome());

            tfEnfermeiroChefe.setText(equipeCirurgica.getEnfermeiroChefe().getNome() + " " + equipeCirurgica.getEnfermeiroChefe().getSobrenome());

            tfInstrumentador.setText(equipeCirurgica.getInstrumentador().getNome() + " " + equipeCirurgica.getInstrumentador().getSobrenome());

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAnterior1;
    private javax.swing.JButton btnAvancar1;
    private javax.swing.JButton btnAvancar2;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnProximo2;
    private javax.swing.JButton btnProximo3;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JButton btnVoltar2;
    private javax.swing.JButton btnVoltar3;
    private javax.swing.JComboBox<String> cbxFuncionarios;
    private javax.swing.JComboBox<String> cbxSalaCirurgica;
    private javax.swing.JFormattedTextField ftfValor;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcData;
    private javax.swing.JLabel jlAnestesista;
    private javax.swing.JLabel jlCirculante;
    private javax.swing.JLabel jlCirurgiaoAssistente;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlHorario;
    private javax.swing.JLabel jlInstrumentador;
    private javax.swing.JLabel jlRelatorio;
    private javax.swing.JLabel jlValor;
    private javax.swing.JPanel jpSalaCirurgia;
    private javax.swing.JPanel jpValorRelatorio;
    private javax.swing.JSpinner jsHora;
    private javax.swing.JSpinner jsMinuto;
    private javax.swing.JLabel ljCirurgiaoPrincipal;
    private javax.swing.JLabel ljEnfermeiroChefe;
    private javax.swing.JTextArea taRelatorio;
    private javax.swing.JTextField tfAnestesista;
    private javax.swing.JTextField tfCirculante;
    private javax.swing.JTextField tfCirurgiaoAssistente;
    private javax.swing.JTextField tfCirurgiaoPrincipal;
    private javax.swing.JTextField tfEnfermeiroChefe;
    private javax.swing.JTextField tfInstrumentador;
    private javax.swing.JTabbedPane tpCirurgia;
    // End of variables declaration//GEN-END:variables
}
