package view;

import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Wanderson_M
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jmNovoPaciente = new javax.swing.JMenuItem();
        jmConsultarPaciente = new javax.swing.JMenuItem();
        jmEditarPaciente = new javax.swing.JMenuItem();
        jmDeletarPaciente = new javax.swing.JMenuItem();
        jmProntuario = new javax.swing.JMenu();
        jmConsultarProntuario = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jmAnestesistaN = new javax.swing.JMenuItem();
        jmCirculanteN = new javax.swing.JMenuItem();
        jmCirurgiaoN = new javax.swing.JMenuItem();
        jmEnfermeiroN = new javax.swing.JMenuItem();
        jmMedicoN = new javax.swing.JMenuItem();
        jmInstrumentadorN = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmAnestesistaC = new javax.swing.JMenuItem();
        jmCirculanteC = new javax.swing.JMenuItem();
        jmCirurgiaoC = new javax.swing.JMenuItem();
        jmEnfermeiroC = new javax.swing.JMenuItem();
        jmMedicoC = new javax.swing.JMenuItem();
        jmInstrumentadorC = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmAnestesistaE = new javax.swing.JMenuItem();
        jmCirculanteE = new javax.swing.JMenuItem();
        jmCirurgiaoE = new javax.swing.JMenuItem();
        jmEnfermeiroE = new javax.swing.JMenuItem();
        jmMedicoE = new javax.swing.JMenuItem();
        jmInstrumentadorE = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmAnestesistaD = new javax.swing.JMenuItem();
        jmCirculanteD = new javax.swing.JMenuItem();
        jmCirurgiaoD = new javax.swing.JMenuItem();
        jmEnfermeiroD = new javax.swing.JMenuItem();
        jmMedicoD = new javax.swing.JMenuItem();
        jmInstrumentadorD = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jmNovoEscala = new javax.swing.JMenuItem();
        jmConsultarEscala = new javax.swing.JMenuItem();
        jmEditarEscala = new javax.swing.JMenuItem();
        jmDeletarEscala = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jmAdicionarEstoque = new javax.swing.JMenuItem();
        jmConsultarEstoque = new javax.swing.JMenuItem();
        jmEditarEstoque = new javax.swing.JMenuItem();
        jmDeletarEstoque = new javax.swing.JMenuItem();

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );

        jMenu11.setText("Paciente");

        jmNovoPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmNovoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/create.png"))); // NOI18N
        jmNovoPaciente.setText("Novo");
        jmNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNovoPacienteActionPerformed(evt);
            }
        });
        jMenu11.add(jmNovoPaciente);

        jmConsultarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmConsultarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/read.png"))); // NOI18N
        jmConsultarPaciente.setText("Consultar");
        jmConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarPacienteActionPerformed(evt);
            }
        });
        jMenu11.add(jmConsultarPaciente);

        jmEditarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmEditarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/update.png"))); // NOI18N
        jmEditarPaciente.setText("Editar");
        jmEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarPacienteActionPerformed(evt);
            }
        });
        jMenu11.add(jmEditarPaciente);

        jmDeletarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmDeletarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete.png"))); // NOI18N
        jmDeletarPaciente.setText("Deletar");
        jmDeletarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDeletarPacienteActionPerformed(evt);
            }
        });
        jMenu11.add(jmDeletarPaciente);

        jmProntuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/arquivo-medico.png"))); // NOI18N
        jmProntuario.setText("Prontuario");

        jmConsultarProntuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmConsultarProntuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/read.png"))); // NOI18N
        jmConsultarProntuario.setText("Consultar");
        jmConsultarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarProntuarioActionPerformed(evt);
            }
        });
        jmProntuario.add(jmConsultarProntuario);

        jMenu11.add(jmProntuario);

        jMenuBar3.add(jMenu11);

        jMenu12.setText("Funcionário");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/create.png"))); // NOI18N
        jMenu1.setText("Novo");

        jmAnestesistaN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmAnestesistaN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/anestesia.png"))); // NOI18N
        jmAnestesistaN.setText("Anestesista");
        jmAnestesistaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAnestesistaNActionPerformed(evt);
            }
        });
        jMenu1.add(jmAnestesistaN);

        jmCirculanteN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmCirculanteN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/enfermeiro.png"))); // NOI18N
        jmCirculanteN.setText("Circulante");
        jmCirculanteN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCirculanteNActionPerformed(evt);
            }
        });
        jMenu1.add(jmCirculanteN);

        jmCirurgiaoN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmCirurgiaoN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cirurgiao.png"))); // NOI18N
        jmCirurgiaoN.setText("Cirurgiã(o)");
        jmCirurgiaoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCirurgiaoNActionPerformed(evt);
            }
        });
        jMenu1.add(jmCirurgiaoN);

        jmEnfermeiroN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmEnfermeiroN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/enfermeira.png"))); // NOI18N
        jmEnfermeiroN.setText("Enferemeiro(a)");
        jmEnfermeiroN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEnfermeiroNActionPerformed(evt);
            }
        });
        jMenu1.add(jmEnfermeiroN);

        jmMedicoN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmMedicoN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/medico.png"))); // NOI18N
        jmMedicoN.setText("Médico(a)");
        jmMedicoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMedicoNActionPerformed(evt);
            }
        });
        jMenu1.add(jmMedicoN);

        jmInstrumentadorN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmInstrumentadorN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/instrumento-cirurgico.png"))); // NOI18N
        jmInstrumentadorN.setText("Instrumentador(a)");
        jmInstrumentadorN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInstrumentadorNActionPerformed(evt);
            }
        });
        jMenu1.add(jmInstrumentadorN);

        jMenu12.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/read.png"))); // NOI18N
        jMenu2.setText(" Consultar");

        jmAnestesistaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/anestesia.png"))); // NOI18N
        jmAnestesistaC.setText("Anestesista");
        jmAnestesistaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAnestesistaCActionPerformed(evt);
            }
        });
        jMenu2.add(jmAnestesistaC);

        jmCirculanteC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/enfermeiro.png"))); // NOI18N
        jmCirculanteC.setText("Circulante");
        jmCirculanteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCirculanteCActionPerformed(evt);
            }
        });
        jMenu2.add(jmCirculanteC);

        jmCirurgiaoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cirurgiao.png"))); // NOI18N
        jmCirurgiaoC.setText("Cirurgiã(o)");
        jmCirurgiaoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCirurgiaoCActionPerformed(evt);
            }
        });
        jMenu2.add(jmCirurgiaoC);

        jmEnfermeiroC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/enfermeira.png"))); // NOI18N
        jmEnfermeiroC.setText("Enferemeiro(a)");
        jmEnfermeiroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEnfermeiroCActionPerformed(evt);
            }
        });
        jMenu2.add(jmEnfermeiroC);

        jmMedicoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/medico.png"))); // NOI18N
        jmMedicoC.setText("Médico(a)");
        jmMedicoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMedicoCActionPerformed(evt);
            }
        });
        jMenu2.add(jmMedicoC);

        jmInstrumentadorC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/instrumento-cirurgico.png"))); // NOI18N
        jmInstrumentadorC.setText("Instrumentador(a)");
        jmInstrumentadorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInstrumentadorCActionPerformed(evt);
            }
        });
        jMenu2.add(jmInstrumentadorC);

        jMenu12.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/update.png"))); // NOI18N
        jMenu3.setText("Editar");

        jmAnestesistaE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/anestesia.png"))); // NOI18N
        jmAnestesistaE.setText("Anestesista");
        jmAnestesistaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAnestesistaEActionPerformed(evt);
            }
        });
        jMenu3.add(jmAnestesistaE);

        jmCirculanteE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/enfermeiro.png"))); // NOI18N
        jmCirculanteE.setText("Circulante");
        jmCirculanteE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCirculanteEActionPerformed(evt);
            }
        });
        jMenu3.add(jmCirculanteE);

        jmCirurgiaoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cirurgiao.png"))); // NOI18N
        jmCirurgiaoE.setText("Cirurgiã(o)");
        jmCirurgiaoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCirurgiaoEActionPerformed(evt);
            }
        });
        jMenu3.add(jmCirurgiaoE);

        jmEnfermeiroE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/enfermeira.png"))); // NOI18N
        jmEnfermeiroE.setText("Enferemeiro(a)");
        jmEnfermeiroE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEnfermeiroEActionPerformed(evt);
            }
        });
        jMenu3.add(jmEnfermeiroE);

        jmMedicoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/medico.png"))); // NOI18N
        jmMedicoE.setText("Médico(a)");
        jmMedicoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMedicoEActionPerformed(evt);
            }
        });
        jMenu3.add(jmMedicoE);

        jmInstrumentadorE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/instrumento-cirurgico.png"))); // NOI18N
        jmInstrumentadorE.setText("Instrumentador(a)");
        jmInstrumentadorE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInstrumentadorEActionPerformed(evt);
            }
        });
        jMenu3.add(jmInstrumentadorE);

        jMenu12.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete.png"))); // NOI18N
        jMenu5.setText("Deletar");

        jmAnestesistaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/anestesia.png"))); // NOI18N
        jmAnestesistaD.setText("Anestesista");
        jmAnestesistaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAnestesistaDActionPerformed(evt);
            }
        });
        jMenu5.add(jmAnestesistaD);

        jmCirculanteD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/enfermeiro.png"))); // NOI18N
        jmCirculanteD.setText("Circulante");
        jmCirculanteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCirculanteDActionPerformed(evt);
            }
        });
        jMenu5.add(jmCirculanteD);

        jmCirurgiaoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cirurgiao.png"))); // NOI18N
        jmCirurgiaoD.setText("Cirurgiã(o)");
        jmCirurgiaoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCirurgiaoDActionPerformed(evt);
            }
        });
        jMenu5.add(jmCirurgiaoD);

        jmEnfermeiroD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/enfermeira.png"))); // NOI18N
        jmEnfermeiroD.setText("Enferemeiro(a)");
        jmEnfermeiroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEnfermeiroDActionPerformed(evt);
            }
        });
        jMenu5.add(jmEnfermeiroD);

        jmMedicoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/medico.png"))); // NOI18N
        jmMedicoD.setText("Médico(a)");
        jmMedicoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMedicoDActionPerformed(evt);
            }
        });
        jMenu5.add(jmMedicoD);

        jmInstrumentadorD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/instrumento-cirurgico.png"))); // NOI18N
        jmInstrumentadorD.setText("Instrumentador(a)");
        jmInstrumentadorD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInstrumentadorDActionPerformed(evt);
            }
        });
        jMenu5.add(jmInstrumentadorD);

        jMenu12.add(jMenu5);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/horario-de-trabalho.png"))); // NOI18N
        jMenu10.setText("Escala");

        jmNovoEscala.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmNovoEscala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/create.png"))); // NOI18N
        jmNovoEscala.setText("Novo");
        jmNovoEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNovoEscalaActionPerformed(evt);
            }
        });
        jMenu10.add(jmNovoEscala);

        jmConsultarEscala.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmConsultarEscala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/read.png"))); // NOI18N
        jmConsultarEscala.setText("Consultar");
        jmConsultarEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarEscalaActionPerformed(evt);
            }
        });
        jMenu10.add(jmConsultarEscala);

        jmEditarEscala.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmEditarEscala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/update.png"))); // NOI18N
        jmEditarEscala.setText("Editar");
        jmEditarEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarEscalaActionPerformed(evt);
            }
        });
        jMenu10.add(jmEditarEscala);

        jmDeletarEscala.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmDeletarEscala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete.png"))); // NOI18N
        jmDeletarEscala.setText("Deletar");
        jmDeletarEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDeletarEscalaActionPerformed(evt);
            }
        });
        jMenu10.add(jmDeletarEscala);

        jMenu12.add(jMenu10);

        jMenuBar3.add(jMenu12);

        jMenu13.setText("Estoque");

        jmAdicionarEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmAdicionarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/create.png"))); // NOI18N
        jmAdicionarEstoque.setText("Adicionar");
        jMenu13.add(jmAdicionarEstoque);

        jmConsultarEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmConsultarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/read.png"))); // NOI18N
        jmConsultarEstoque.setText("Consultar");
        jMenu13.add(jmConsultarEstoque);

        jmEditarEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmEditarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/update.png"))); // NOI18N
        jmEditarEstoque.setText("Editar");
        jMenu13.add(jmEditarEstoque);

        jmDeletarEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmDeletarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete.png"))); // NOI18N
        jmDeletarEstoque.setText("Deletar");
        jMenu13.add(jmDeletarEstoque);

        jMenuBar3.add(jMenu13);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNovoPacienteActionPerformed
        PessoaCadastrar paciente = new PessoaCadastrar("paciente", "Paciente");
        jDesktopPane.add(paciente);
        paciente.setTitle("Paciente");
        paciente.setVisible(true);

////NewJInternalFrame teste = new  NewJInternalFrame();
////jDesktopPane.add(teste);
//teste.setVisible(true);

    }//GEN-LAST:event_jmNovoPacienteActionPerformed
//Novo-----------------------------------------------------------------------------
    private void jmAnestesistaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAnestesistaNActionPerformed
        PessoaCadastrar anestesista = new PessoaCadastrar("funcionario", "Anestesista");
        jDesktopPane.add(anestesista);
        anestesista.setTitle("Anestesista");
        anestesista.setVisible(true);
    }//GEN-LAST:event_jmAnestesistaNActionPerformed

    private void jmCirculanteNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCirculanteNActionPerformed
        PessoaCadastrar circulante = new PessoaCadastrar("funcionario", "Circulante");
        jDesktopPane.add(circulante);
        circulante.setTitle("Circulante");
        circulante.setVisible(true);    }//GEN-LAST:event_jmCirculanteNActionPerformed

    private void jmCirurgiaoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCirurgiaoNActionPerformed
        PessoaCadastrar cirurgiao = new PessoaCadastrar("funcionario", "Cirurgiã(ão)");
        jDesktopPane.add(cirurgiao);
        cirurgiao.setTitle("Cirurgiã(o)");
        cirurgiao.setVisible(true);
     }//GEN-LAST:event_jmCirurgiaoNActionPerformed

    private void jmEnfermeiroNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEnfermeiroNActionPerformed
        PessoaCadastrar enfermeiro = new PessoaCadastrar("funcionario", "Enfermeiro(a)");
        jDesktopPane.add(enfermeiro);
        enfermeiro.setTitle("Enfermeiro(a)");
        enfermeiro.setVisible(true);
     }//GEN-LAST:event_jmEnfermeiroNActionPerformed

    private void jmMedicoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMedicoNActionPerformed
        PessoaCadastrar medico = new PessoaCadastrar("funcionario", "Medico");
        jDesktopPane.add(medico);
        medico.setTitle("Medico(a)");
        medico.setVisible(true);     }//GEN-LAST:event_jmMedicoNActionPerformed

    private void jmInstrumentadorNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInstrumentadorNActionPerformed
        PessoaCadastrar instrumentador = new PessoaCadastrar("funcionario", "Instrumentador(a)");
        jDesktopPane.add(instrumentador);
        instrumentador.setTitle("Instrumentador(a)");
        instrumentador.setVisible(true);
    }//GEN-LAST:event_jmInstrumentadorNActionPerformed
//Paciente.
    private void jmConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarPacienteActionPerformed
        PessoaConsultar pacienteConsultar = new PessoaConsultar("paciente", "paciente");
        jDesktopPane.add(pacienteConsultar);
        pacienteConsultar.setTitle("Paciente");
        pacienteConsultar.setVisible(true);
    }//GEN-LAST:event_jmConsultarPacienteActionPerformed

    private void jmEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarPacienteActionPerformed
        PessoaEditar pacienteEditar = new PessoaEditar("paciente", "paciente");
        jDesktopPane.add(pacienteEditar);
        pacienteEditar.setTitle("Editar paciente");
        pacienteEditar.setVisible(true);    }//GEN-LAST:event_jmEditarPacienteActionPerformed

    private void jmDeletarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDeletarPacienteActionPerformed
        PessoaDeletar pacienteDeletar = new PessoaDeletar("paciente", "paciente");
        jDesktopPane.add(pacienteDeletar);
        pacienteDeletar.setTitle("Deletar paciente");
        pacienteDeletar.setVisible(true);
     }//GEN-LAST:event_jmDeletarPacienteActionPerformed

    private void jmConsultarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarProntuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmConsultarProntuarioActionPerformed
//Paciente----------------------------------------------------------------------------

//Funcionario-------------------------------------------------------------------------
//Consulta----------------------------------------------------------------------------

    private void jmAnestesistaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAnestesistaCActionPerformed
        PessoaConsultar anestesistaConsultar = new PessoaConsultar("funcionario", "Anestesista");
        jDesktopPane.add(anestesistaConsultar);
        anestesistaConsultar.setTitle("Consultar anestesista");
        anestesistaConsultar.setVisible(true);    }//GEN-LAST:event_jmAnestesistaCActionPerformed

    private void jmCirculanteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCirculanteCActionPerformed
        PessoaConsultar circulanteConsultar = new PessoaConsultar("funcionario", "Circulante");
        jDesktopPane.add(circulanteConsultar);
        circulanteConsultar.setTitle("Consultar circulante");
        circulanteConsultar.setVisible(true);    }//GEN-LAST:event_jmCirculanteCActionPerformed

    private void jmCirurgiaoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCirurgiaoCActionPerformed
        PessoaConsultar cirurgiaoConsultar = new PessoaConsultar("funcionario", "Cirurgiã(o)");
        jDesktopPane.add(cirurgiaoConsultar);
        cirurgiaoConsultar.setTitle("Consultar cirurgiã(o)");
        cirurgiaoConsultar.setVisible(true);    }//GEN-LAST:event_jmCirurgiaoCActionPerformed

    private void jmEnfermeiroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEnfermeiroCActionPerformed
        PessoaConsultar enfermeiroConsultar = new PessoaConsultar("funcionario", "Enfermeiro(a)");
        jDesktopPane.add(enfermeiroConsultar);
        enfermeiroConsultar.setTitle("Consultar enfermeiro(a)");
        enfermeiroConsultar.setVisible(true);    }//GEN-LAST:event_jmEnfermeiroCActionPerformed

    private void jmMedicoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMedicoCActionPerformed
        PessoaConsultar medicoConsultar = new PessoaConsultar("funcionario", "Medico(a)");
        jDesktopPane.add(medicoConsultar);
        medicoConsultar.setTitle("Consultar medico(a)");
        medicoConsultar.setVisible(true);     }//GEN-LAST:event_jmMedicoCActionPerformed

    private void jmInstrumentadorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInstrumentadorCActionPerformed
        PessoaConsultar instrumentadorConsultar = new PessoaConsultar("funcionario", "Instrumentador(a)");
        jDesktopPane.add(instrumentadorConsultar);
        instrumentadorConsultar.setTitle("Consultar instrumentador(a)");
        instrumentadorConsultar.setVisible(true);    }//GEN-LAST:event_jmInstrumentadorCActionPerformed

//Editar---------------------------------------------------------------------------

    private void jmAnestesistaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAnestesistaEActionPerformed
        PessoaEditar anestesistaEditar = new PessoaEditar("funcionario", "Anestesista");
        jDesktopPane.add(anestesistaEditar);
        anestesistaEditar.setTitle("Editar anestesista");
        anestesistaEditar.setVisible(true);    }//GEN-LAST:event_jmAnestesistaEActionPerformed

    private void jmCirculanteEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCirculanteEActionPerformed
        PessoaEditar circulanteEditar = new PessoaEditar("funcionario", "Circulante");
        jDesktopPane.add(circulanteEditar);
        circulanteEditar.setTitle("Editar circulante");
        circulanteEditar.setVisible(true);    }//GEN-LAST:event_jmCirculanteEActionPerformed

    private void jmCirurgiaoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCirurgiaoEActionPerformed
        PessoaEditar cirurgiaoEditar = new PessoaEditar("funcionario", "Cirurgiã(o)");
        jDesktopPane.add(cirurgiaoEditar);
        cirurgiaoEditar.setTitle("Editar cirurgiã(o)");
        cirurgiaoEditar.setVisible(true);    }//GEN-LAST:event_jmCirurgiaoEActionPerformed

    private void jmEnfermeiroEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEnfermeiroEActionPerformed
        PessoaEditar enfermeiroEditar = new PessoaEditar("funcionario", "Enfermeiro(a)");
        jDesktopPane.add(enfermeiroEditar);
        enfermeiroEditar.setTitle("Editar enfermeiro(a)");
        enfermeiroEditar.setVisible(true);     }//GEN-LAST:event_jmEnfermeiroEActionPerformed

    private void jmMedicoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMedicoEActionPerformed
        PessoaEditar medicoEditar = new PessoaEditar("funcionario", "Medico(a)");
        jDesktopPane.add(medicoEditar);
        medicoEditar.setTitle("Editar medico(a)");
        medicoEditar.setVisible(true);     }//GEN-LAST:event_jmMedicoEActionPerformed

    private void jmInstrumentadorEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInstrumentadorEActionPerformed
        PessoaEditar instrumentadorEditar = new PessoaEditar("funcionario", "Instrumentador(a)");
        jDesktopPane.add(instrumentadorEditar);
        instrumentadorEditar.setTitle("Editar instrumentador(a)");
        instrumentadorEditar.setVisible(true);    }//GEN-LAST:event_jmInstrumentadorEActionPerformed

//Deletar-------------------------------------------------------------------------

    private void jmAnestesistaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAnestesistaDActionPerformed
        PessoaDeletar anestesistaDeletar = new PessoaDeletar("funcionario", "Anestesista");
        jDesktopPane.add(anestesistaDeletar);
        anestesistaDeletar.setTitle("Deletar anestesista");
        anestesistaDeletar.setVisible(true);     }//GEN-LAST:event_jmAnestesistaDActionPerformed

    private void jmCirculanteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCirculanteDActionPerformed
        PessoaDeletar circulanteDeletar = new PessoaDeletar("funcionario", "Circulante");
        jDesktopPane.add(circulanteDeletar);
        circulanteDeletar.setTitle("Deletar circulante");
        circulanteDeletar.setVisible(true);    }//GEN-LAST:event_jmCirculanteDActionPerformed

    private void jmCirurgiaoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCirurgiaoDActionPerformed
        PessoaDeletar cirurgiaoDeletar = new PessoaDeletar("funcionario", "Cirurgiã(o)");
        jDesktopPane.add(cirurgiaoDeletar);
        cirurgiaoDeletar.setTitle("Deletar cirurgiã(o)");
        cirurgiaoDeletar.setVisible(true);     }//GEN-LAST:event_jmCirurgiaoDActionPerformed

    private void jmEnfermeiroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEnfermeiroDActionPerformed
        PessoaDeletar enfermeiroDeletar = new PessoaDeletar("funcionario", "Enfermeiro(a)");
        jDesktopPane.add(enfermeiroDeletar);
        enfermeiroDeletar.setTitle("Deletar enfermeiro(a)");
        enfermeiroDeletar.setVisible(true);     }//GEN-LAST:event_jmEnfermeiroDActionPerformed

    private void jmMedicoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMedicoDActionPerformed
        PessoaDeletar medicoDeletar = new PessoaDeletar("funcionario", "Medico(a)");
        jDesktopPane.add(medicoDeletar);
        medicoDeletar.setTitle("Deletar medico(a)");
        medicoDeletar.setVisible(true);    }//GEN-LAST:event_jmMedicoDActionPerformed

    private void jmInstrumentadorDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInstrumentadorDActionPerformed
        PessoaDeletar instrumentadorDeletar = new PessoaDeletar("funcionario", "Instrumentador(a)");
        jDesktopPane.add(instrumentadorDeletar);
        instrumentadorDeletar.setTitle("Deletar instrumentador(a)");
        instrumentadorDeletar.setVisible(true);    }//GEN-LAST:event_jmInstrumentadorDActionPerformed
//Escala-----------------------------------------------------------------------------
    private void jmNovoEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNovoEscalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmNovoEscalaActionPerformed

    private void jmConsultarEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarEscalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmConsultarEscalaActionPerformed

    private void jmEditarEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarEscalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmEditarEscalaActionPerformed

    private void jmDeletarEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDeletarEscalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmDeletarEscalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jmAdicionarEstoque;
    private javax.swing.JMenuItem jmAnestesistaC;
    private javax.swing.JMenuItem jmAnestesistaD;
    private javax.swing.JMenuItem jmAnestesistaE;
    private javax.swing.JMenuItem jmAnestesistaN;
    private javax.swing.JMenuItem jmCirculanteC;
    private javax.swing.JMenuItem jmCirculanteD;
    private javax.swing.JMenuItem jmCirculanteE;
    private javax.swing.JMenuItem jmCirculanteN;
    private javax.swing.JMenuItem jmCirurgiaoC;
    private javax.swing.JMenuItem jmCirurgiaoD;
    private javax.swing.JMenuItem jmCirurgiaoE;
    private javax.swing.JMenuItem jmCirurgiaoN;
    private javax.swing.JMenuItem jmConsultarEscala;
    private javax.swing.JMenuItem jmConsultarEstoque;
    private javax.swing.JMenuItem jmConsultarPaciente;
    private javax.swing.JMenuItem jmConsultarProntuario;
    private javax.swing.JMenuItem jmDeletarEscala;
    private javax.swing.JMenuItem jmDeletarEstoque;
    private javax.swing.JMenuItem jmDeletarPaciente;
    private javax.swing.JMenuItem jmEditarEscala;
    private javax.swing.JMenuItem jmEditarEstoque;
    private javax.swing.JMenuItem jmEditarPaciente;
    private javax.swing.JMenuItem jmEnfermeiroC;
    private javax.swing.JMenuItem jmEnfermeiroD;
    private javax.swing.JMenuItem jmEnfermeiroE;
    private javax.swing.JMenuItem jmEnfermeiroN;
    private javax.swing.JMenuItem jmInstrumentadorC;
    private javax.swing.JMenuItem jmInstrumentadorD;
    private javax.swing.JMenuItem jmInstrumentadorE;
    private javax.swing.JMenuItem jmInstrumentadorN;
    private javax.swing.JMenuItem jmMedicoC;
    private javax.swing.JMenuItem jmMedicoD;
    private javax.swing.JMenuItem jmMedicoE;
    private javax.swing.JMenuItem jmMedicoN;
    private javax.swing.JMenuItem jmNovoEscala;
    private javax.swing.JMenuItem jmNovoPaciente;
    private javax.swing.JMenu jmProntuario;
    // End of variables declaration//GEN-END:variables
}
