/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GerenciaPagamento;
import dao.ParametrosDao;
import dao.PagamentoDao;
import dao.ProntuarioDao;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Juros;
import model.Pagamento;
import model.Parametro;
import model.Parcela;

/**
 *
 * @author Wanderson_M
 */
public class PagamentoDinheiroDebito extends javax.swing.JInternalFrame {

    /**
     * Creates new form PagamentoComposto
     */
    ArrayList<model.Prontuario> prontuarios;
    ArrayList<model.Prontuario> prontuariosNaoPagos;
    ArrayList<model.Paciente> pacientes;
    ProntuarioDao pd;
    Juros juros;
    float soma;
    private float descontoMaximo = 0;
    DecimalFormat df;
    private Parametro parametros;
    private ParametrosDao parametrosDao;
    float descontoAplicado = 0;
    
    public PagamentoDinheiroDebito() {
        parametrosDao = ParametrosDao.getInstance();
        
        pd = ProntuarioDao.getInstance();
        prontuarios = pd.listarNaoPagos();
        pacientes = pd.listarPacientesNaoPagosSemRepetir();
        df = new DecimalFormat("#,###.00");
        initComponents();
        ftfDesconto.setText("0");
        if (pacientes == null) {
            JOptionPane.showMessageDialog(this, "Nenhuma paciente com alta pendente !");
            btnSalvar.setEnabled(false);
            btnDesconto.setEnabled(false);
            dispose();
        } else {
            preencheCampos();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPacientes = new javax.swing.JTable();
        tfValorTotal = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtProntuarios = new javax.swing.JTable();
        cbxDinheiroDebito = new javax.swing.JComboBox<>();
        ftfDesconto = new javax.swing.JFormattedTextField();
        btnDesconto = new javax.swing.JButton();
        tfDescontoMaximo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);
        setTitle("Pagamento juros composto"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jtPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtPacientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tfValorTotal.setEditable(false);
        tfValorTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Pagar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prontuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jtProntuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtProntuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProntuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtProntuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        cbxDinheiroDebito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Débito" }));

        ftfDesconto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desconto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnDesconto.setText("Aplicar desconto");
        btnDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontoActionPerformed(evt);
            }
        });

        tfDescontoMaximo.setEditable(false);
        tfDescontoMaximo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Desconto maximo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jMenu1.setText("File");

        jMenuItem1.setText("Alterar porcentagem do desconto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cbxDinheiroDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(tfDescontoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnFechar))
                                    .addComponent(tfValorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfDesconto)
                            .addComponent(btnDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDescontoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxDinheiroDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesconto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPacientesMouseClicked
        if (jtPacientes.getSelectedRow() != -1) {
            prontuariosNaoPagos = new ArrayList();
            
            for (int j = 0; j < prontuarios.size(); j++) {
                if (pacientes.get(jtPacientes.getSelectedRow()).getNome().equals(prontuarios.get(j).getPaciente().getNome())) {
                    prontuariosNaoPagos.add(prontuarios.get(j));
                }
            }
            System.out.println("Tamanho p: " + prontuariosNaoPagos.size());
            
            Object[][] valores = new Object[prontuariosNaoPagos.size()][3];
            for (int i = 0; i < prontuariosNaoPagos.size(); i++) {
                
                valores[i][0] = prontuariosNaoPagos.get(i).getData();
                valores[i][1] = prontuariosNaoPagos.get(i).getHora();
                valores[i][2] = prontuariosNaoPagos.get(i).getMedico().getNome() + " " + prontuariosNaoPagos.get(i).getMedico().getSobrenome();
                
            }
            DefaultTableModel model = new DefaultTableModel(valores, new String[]{"Data", "Hora", "Médico"});
            jtProntuarios.setModel(model);

        }     }//GEN-LAST:event_jtPacientesMouseClicked

    private void jtProntuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProntuariosMouseClicked
        campos();
        

    }//GEN-LAST:event_jtProntuariosMouseClicked
    
    public void campos() {
        parametros = parametrosDao.recuperar();
        
        if (jtProntuarios.getSelectedRow() != -1) {
            soma = 0;
            model.Prontuario p = prontuariosNaoPagos.get(jtProntuarios.getSelectedRow());
            if (p.getCirurgias() != null) {
                for (int i = 0; i < p.getCirurgias().size(); i++) {
                    soma += p.getCirurgias().get(i).getValor();
                    
                }
                
            }
            if (p.getExames() != null) {
                for (int i = 0; i < p.getExames().size(); i++) {
                    soma += p.getExames().get(i).getValor();
                }
                
            }
            if (p.getMedicamentos() != null) {
                for (int i = 0; i < p.getMedicamentos().size(); i++) {
                    soma += p.getMedicamentos().get(i).getPreco();
                }
                
            }
            tfValorTotal.setText("R$ " + df.format(soma));
            descontoMaximo = soma * (parametros.getDescontoPorcentagem() / 100);
            tfDescontoMaximo.setText(df.format(descontoMaximo));
        }
        
    }
    

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        int e = JOptionPane.showConfirmDialog(this, "Deseja Fechar ?", "", JOptionPane.OK_CANCEL_OPTION);
        if (e == JOptionPane.OK_OPTION) {
            dispose();

        }     }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            GerenciaPagamento gp = GerenciaPagamento.getInstance();
            float juros = 0;
            ArrayList<Parcela> parcelas = new ArrayList();
            Parcela parcela = new Parcela(1, soma, LocalDate.now(), juros, descontoAplicado, LocalDate.now(), 0);
            parcelas.add(parcela);
            
            System.out.println("Valor: " + parcela.getValor());
            Pagamento pagamento = new Pagamento();
            pagamento.setParcelas(parcelas);
            pagamento.setProntuario(prontuarios.get(jtProntuarios.getSelectedRow()));
            String tipo;
            if (cbxDinheiroDebito.getSelectedIndex() == 0) {
                tipo = "Dinheiro";
            } else {
                tipo = "Débito";
            }
            pagamento.setTipo(tipo);
            int r = gp.gerarPagamento(pagamento);
            r = 0;
            r = gp.pagar(parcela);
            if (r == 1) {
                JOptionPane.showMessageDialog(this, "Pagamento efetuado com sucesso !");
                dispose();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao efetuar pagamento !");
            
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed
    

    private void btnDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontoActionPerformed
        
        if (jtProntuarios.getSelectedRow() != -1) {
            try {
                descontoAplicado += Float.valueOf(ftfDesconto.getText()).floatValue();
                if (descontoAplicado > descontoMaximo) {
                    JOptionPane.showMessageDialog(this, "Erro ! Valor maximo de desconto : R$ " + df.format(descontoMaximo));
                    descontoAplicado = 0;
                    campos();
                } else {
                    System.out.println("TTTT");
                    soma -= descontoAplicado;
                    tfValorTotal.setText(df.format(soma));
                    
                }
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Informe o valor corretamente.");
            }
            
        }
    }//GEN-LAST:event_btnDescontoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DescontoPorcentagem descontoPorcentagem = new DescontoPorcentagem(new JFrame(), true, this);
        descontoPorcentagem.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    public void preencheCampos() {
        
        Object[][] valores = new Object[pacientes.size()][2];
        for (int i = 0; i < pacientes.size(); i++) {
            valores[i][0] = pacientes.get(i).getNome();
            valores[i][1] = pacientes.get(i).getSobrenome();
            
        }
        
        DefaultTableModel model = new DefaultTableModel(valores, new String[]{"Nome", "Sobrenome"});
        jtPacientes.setModel(model);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesconto;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxDinheiroDebito;
    private javax.swing.JFormattedTextField ftfDesconto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtPacientes;
    private javax.swing.JTable jtProntuarios;
    private javax.swing.JTextField tfDescontoMaximo;
    private javax.swing.JTextField tfValorTotal;
    // End of variables declaration//GEN-END:variables
}
