/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mae;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Wanderson_M
 */
public abstract class EquipeCirurgica extends javax.swing.JInternalFrame {

    /**
     * Creates new form EquipeCirurgicaMae
     */
    public EquipeCirurgica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCampos = new javax.swing.JPanel();
        cbxCirurgiaoPrincipal = new javax.swing.JComboBox<>();
        jlCirurgiaoPrincipal = new javax.swing.JLabel();
        jlCirurgiaoAssistente = new javax.swing.JLabel();
        cbxCirurgiaoAssistente = new javax.swing.JComboBox<>();
        jlEnfermeiroChefe = new javax.swing.JLabel();
        jlAnestesista = new javax.swing.JLabel();
        cbxAnestesista = new javax.swing.JComboBox<>();
        cbxEnfermeiroChefe = new javax.swing.JComboBox<>();
        jlCirculante = new javax.swing.JLabel();
        jlInstrumentador = new javax.swing.JLabel();
        cbxInstrumentador = new javax.swing.JComboBox<>();
        cbxCirculante = new javax.swing.JComboBox<>();
        btnAcao = new javax.swing.JButton();
        btnProximoCirculante = new javax.swing.JButton();
        btnAnteriorCirculante = new javax.swing.JButton();
        btnAnteriorAnestesista = new javax.swing.JButton();
        btnProximoAnestesista = new javax.swing.JButton();
        btnAnteriorInstrumentador = new javax.swing.JButton();
        btnProximoInstrumentador = new javax.swing.JButton();
        btnAnteriorEnfermeiroChefe = new javax.swing.JButton();
        btnProximoEnfermeiroChefe = new javax.swing.JButton();
        btnAnteriorCirurgiaoPrincipal = new javax.swing.JButton();
        btnProximoCirurgiaoPrincipal = new javax.swing.JButton();
        btnAnteriorCirurgiaoAssistente = new javax.swing.JButton();
        btnProximoCirurgiaoAssistente = new javax.swing.JButton();

        jlCirurgiaoPrincipal.setText("Cirurgiao Principal");

        jlCirurgiaoAssistente.setText("Cirurgiao Assistente");

        jlEnfermeiroChefe.setText("Enfermeiro Chefe");

        jlAnestesista.setText("Anestesista");

        jlCirculante.setText("Circulante");

        jlInstrumentador.setText("Instrumentador");

        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        btnProximoCirculante.setText(">>");
        btnProximoCirculante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoCirculanteActionPerformed(evt);
            }
        });

        btnAnteriorCirculante.setText("<<");
        btnAnteriorCirculante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorCirculanteActionPerformed(evt);
            }
        });

        btnAnteriorAnestesista.setText("<<");
        btnAnteriorAnestesista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorAnestesistaActionPerformed(evt);
            }
        });

        btnProximoAnestesista.setText(">>");
        btnProximoAnestesista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoAnestesistaActionPerformed(evt);
            }
        });

        btnAnteriorInstrumentador.setText("<<");
        btnAnteriorInstrumentador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorInstrumentadorActionPerformed(evt);
            }
        });

        btnProximoInstrumentador.setText(">>");
        btnProximoInstrumentador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoInstrumentadorActionPerformed(evt);
            }
        });

        btnAnteriorEnfermeiroChefe.setText("<<");
        btnAnteriorEnfermeiroChefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorEnfermeiroChefeActionPerformed(evt);
            }
        });

        btnProximoEnfermeiroChefe.setText(">>");
        btnProximoEnfermeiroChefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoEnfermeiroChefeActionPerformed(evt);
            }
        });

        btnAnteriorCirurgiaoPrincipal.setText("<<");
        btnAnteriorCirurgiaoPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorCirurgiaoPrincipalActionPerformed(evt);
            }
        });

        btnProximoCirurgiaoPrincipal.setText(">>");
        btnProximoCirurgiaoPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoCirurgiaoPrincipalActionPerformed(evt);
            }
        });

        btnAnteriorCirurgiaoAssistente.setText("<<");
        btnAnteriorCirurgiaoAssistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorCirurgiaoAssistenteActionPerformed(evt);
            }
        });

        btnProximoCirurgiaoAssistente.setText(">>");
        btnProximoCirurgiaoAssistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoCirurgiaoAssistenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCamposLayout = new javax.swing.GroupLayout(jpCampos);
        jpCampos.setLayout(jpCamposLayout);
        jpCamposLayout.setHorizontalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAcao)
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCirurgiaoAssistente)
                            .addComponent(jlCirculante)
                            .addComponent(jlAnestesista)
                            .addComponent(jlInstrumentador)
                            .addComponent(jlCirurgiaoPrincipal)
                            .addComponent(jlEnfermeiroChefe))
                        .addGap(18, 18, 18)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxCirurgiaoPrincipal, 0, 182, Short.MAX_VALUE)
                            .addComponent(cbxEnfermeiroChefe, 0, 182, Short.MAX_VALUE)
                            .addComponent(cbxInstrumentador, 0, 182, Short.MAX_VALUE)
                            .addComponent(cbxAnestesista, 0, 182, Short.MAX_VALUE)
                            .addComponent(cbxCirculante, 0, 182, Short.MAX_VALUE)
                            .addComponent(cbxCirurgiaoAssistente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addComponent(btnAnteriorCirculante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProximoCirculante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addComponent(btnAnteriorAnestesista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProximoAnestesista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addComponent(btnAnteriorInstrumentador, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProximoInstrumentador, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addComponent(btnAnteriorEnfermeiroChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProximoEnfermeiroChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addComponent(btnAnteriorCirurgiaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProximoCirurgiaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addComponent(btnAnteriorCirurgiaoAssistente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProximoCirurgiaoAssistente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCamposLayout.setVerticalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCirculante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCirculante)
                    .addComponent(btnAnteriorCirculante)
                    .addComponent(btnProximoCirculante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnteriorAnestesista)
                        .addComponent(btnProximoAnestesista))
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxAnestesista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlAnestesista)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnteriorInstrumentador)
                        .addComponent(btnProximoInstrumentador))
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxInstrumentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlInstrumentador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnteriorEnfermeiroChefe)
                        .addComponent(btnProximoEnfermeiroChefe))
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxEnfermeiroChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlEnfermeiroChefe)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnteriorCirurgiaoPrincipal)
                        .addComponent(btnProximoCirurgiaoPrincipal))
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxCirurgiaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCirurgiaoPrincipal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnteriorCirurgiaoAssistente)
                        .addComponent(btnProximoCirurgiaoAssistente))
                    .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxCirurgiaoAssistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCirurgiaoAssistente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximoCirculanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoCirculanteActionPerformed

        if (cbxCirculante.getSelectedIndex() + 1 >= cbxCirculante.getItemCount()) {
            cbxCirculante.setSelectedIndex(0);
        } else {

            cbxCirculante.setSelectedIndex(cbxCirculante.getSelectedIndex() + 1);
        }


    }//GEN-LAST:event_btnProximoCirculanteActionPerformed

    private void btnAnteriorCirculanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorCirculanteActionPerformed

        if (cbxCirculante.getSelectedIndex() - 1 < 0) {
            cbxCirculante.setSelectedIndex(cbxCirculante.getItemCount() - 1);
        } else {

            cbxCirculante.setSelectedIndex(cbxCirculante.getSelectedIndex() - 1);
        }


    }//GEN-LAST:event_btnAnteriorCirculanteActionPerformed

    private void btnAnteriorAnestesistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorAnestesistaActionPerformed

        if (cbxAnestesista.getSelectedIndex() - 1 < 0) {
            cbxAnestesista.setSelectedIndex(cbxAnestesista.getItemCount() - 1);
        } else {

            cbxAnestesista.setSelectedIndex(cbxAnestesista.getSelectedIndex() - 1);
        }
    }//GEN-LAST:event_btnAnteriorAnestesistaActionPerformed

    private void btnProximoAnestesistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoAnestesistaActionPerformed
        if (cbxAnestesista.getSelectedIndex() + 1 >= cbxAnestesista.getItemCount()) {
            cbxAnestesista.setSelectedIndex(0);
        } else {

            cbxAnestesista.setSelectedIndex(cbxAnestesista.getSelectedIndex() + 1);
        }    
    }//GEN-LAST:event_btnProximoAnestesistaActionPerformed

    private void btnAnteriorInstrumentadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorInstrumentadorActionPerformed
        if (cbxInstrumentador.getSelectedIndex() - 1 < 0) {
            cbxInstrumentador.setSelectedIndex(cbxInstrumentador.getItemCount() - 1);
        } else {

            cbxInstrumentador.setSelectedIndex(cbxInstrumentador.getSelectedIndex() - 1);
        }    
    }//GEN-LAST:event_btnAnteriorInstrumentadorActionPerformed

    private void btnProximoInstrumentadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoInstrumentadorActionPerformed
        if (cbxInstrumentador.getSelectedIndex() + 1 >= cbxInstrumentador.getItemCount()) {
            cbxInstrumentador.setSelectedIndex(0);
        } else {

            cbxInstrumentador.setSelectedIndex(cbxInstrumentador.getSelectedIndex() + 1);
        }    
    }//GEN-LAST:event_btnProximoInstrumentadorActionPerformed

    private void btnAnteriorEnfermeiroChefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorEnfermeiroChefeActionPerformed
        if (cbxEnfermeiroChefe.getSelectedIndex() - 1 < 0) {
            cbxEnfermeiroChefe.setSelectedIndex(cbxEnfermeiroChefe.getItemCount() - 1);
        } else {

            cbxEnfermeiroChefe.setSelectedIndex(cbxEnfermeiroChefe.getSelectedIndex() - 1);
        }   
     }//GEN-LAST:event_btnAnteriorEnfermeiroChefeActionPerformed

    private void btnProximoEnfermeiroChefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoEnfermeiroChefeActionPerformed
        if (cbxEnfermeiroChefe.getSelectedIndex() + 1 >= cbxEnfermeiroChefe.getItemCount()) {
            cbxEnfermeiroChefe.setSelectedIndex(0);
        } else {

            cbxEnfermeiroChefe.setSelectedIndex(cbxEnfermeiroChefe.getSelectedIndex() + 1);
        }    
    }//GEN-LAST:event_btnProximoEnfermeiroChefeActionPerformed

    private void btnAnteriorCirurgiaoPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorCirurgiaoPrincipalActionPerformed
        if (cbxCirurgiaoPrincipal.getSelectedIndex() - 1 < 0) {
            cbxCirurgiaoPrincipal.setSelectedIndex(cbxCirurgiaoPrincipal.getItemCount() - 1);
        } else {

            cbxCirurgiaoPrincipal.setSelectedIndex(cbxCirurgiaoPrincipal.getSelectedIndex() - 1);
        }   
     }//GEN-LAST:event_btnAnteriorCirurgiaoPrincipalActionPerformed

    private void btnProximoCirurgiaoPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoCirurgiaoPrincipalActionPerformed
        if (cbxCirurgiaoPrincipal.getSelectedIndex() + 1 >= cbxCirurgiaoPrincipal.getItemCount()) {
            cbxCirurgiaoPrincipal.setSelectedIndex(0);
        } else {

            cbxCirurgiaoPrincipal.setSelectedIndex(cbxCirurgiaoPrincipal.getSelectedIndex() + 1);
        }    
    }//GEN-LAST:event_btnProximoCirurgiaoPrincipalActionPerformed

    private void btnAnteriorCirurgiaoAssistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorCirurgiaoAssistenteActionPerformed
        if (cbxCirurgiaoAssistente.getSelectedIndex() - 1 < 0) {
            cbxCirurgiaoAssistente.setSelectedIndex(cbxCirurgiaoAssistente.getItemCount() - 1);
        } else {

            cbxCirurgiaoAssistente.setSelectedIndex(cbxCirurgiaoAssistente.getSelectedIndex() - 1);
        }    
    }//GEN-LAST:event_btnAnteriorCirurgiaoAssistenteActionPerformed

    private void btnProximoCirurgiaoAssistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoCirurgiaoAssistenteActionPerformed
        if (cbxCirurgiaoAssistente.getSelectedIndex() + 1 >= cbxCirurgiaoAssistente.getItemCount()) {
            cbxCirurgiaoAssistente.setSelectedIndex(0);
        } else {

            cbxCirurgiaoAssistente.setSelectedIndex(cbxCirurgiaoAssistente.getSelectedIndex() + 1);
        }    
    }//GEN-LAST:event_btnProximoCirurgiaoAssistenteActionPerformed

    public abstract void btnAcaoActionPerformed(java.awt.event.ActionEvent evt);

    public JButton getBtnAcao() {
        return btnAcao;
    }

    public JComboBox<String> getCbxAnestesista() {
        return cbxAnestesista;
    }

    public JComboBox<String> getCbxCirculante() {
        return cbxCirculante;
    }

    public JComboBox<String> getCbxCirurgiaoAssistente() {
        return cbxCirurgiaoAssistente;
    }

    public JComboBox<String> getCbxCirurgiaoPrincipal() {
        return cbxCirurgiaoPrincipal;
    }

    public JComboBox<String> getCbxEnfermeiroChefe() {
        return cbxEnfermeiroChefe;
    }

    public JComboBox<String> getCbxInstrumentador() {
        return cbxInstrumentador;
    }

    public JPanel getJpCampos() {
        return jpCampos;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnAnteriorAnestesista;
    private javax.swing.JButton btnAnteriorCirculante;
    private javax.swing.JButton btnAnteriorCirurgiaoAssistente;
    private javax.swing.JButton btnAnteriorCirurgiaoPrincipal;
    private javax.swing.JButton btnAnteriorEnfermeiroChefe;
    private javax.swing.JButton btnAnteriorInstrumentador;
    private javax.swing.JButton btnProximoAnestesista;
    private javax.swing.JButton btnProximoCirculante;
    private javax.swing.JButton btnProximoCirurgiaoAssistente;
    private javax.swing.JButton btnProximoCirurgiaoPrincipal;
    private javax.swing.JButton btnProximoEnfermeiroChefe;
    private javax.swing.JButton btnProximoInstrumentador;
    private javax.swing.JComboBox<String> cbxAnestesista;
    private javax.swing.JComboBox<String> cbxCirculante;
    private javax.swing.JComboBox<String> cbxCirurgiaoAssistente;
    private javax.swing.JComboBox<String> cbxCirurgiaoPrincipal;
    private javax.swing.JComboBox<String> cbxEnfermeiroChefe;
    private javax.swing.JComboBox<String> cbxInstrumentador;
    private javax.swing.JLabel jlAnestesista;
    private javax.swing.JLabel jlCirculante;
    private javax.swing.JLabel jlCirurgiaoAssistente;
    private javax.swing.JLabel jlCirurgiaoPrincipal;
    private javax.swing.JLabel jlEnfermeiroChefe;
    private javax.swing.JLabel jlInstrumentador;
    private javax.swing.JPanel jpCampos;
    // End of variables declaration//GEN-END:variables
}
