/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mae;

import controller.GerenciaEquipeCirurgica;
import dao.EquipeCirurgicaDao;
import dao.FuncionarioDao;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.EquipeCirurgica;
import model.Funcionario;

/**
 *
 * @author Wanderson_M
 */
public abstract class EquipeCirurgicaCE extends javax.swing.JInternalFrame {

    /**
     * Creates new form EquipeCirurgicaCons
     */
    GerenciaEquipeCirurgica gec;
    protected ArrayList<model.EquipeCirurgica> ecs;
    FuncionarioDao fd;
    EquipeCirurgicaDao ecd;

    public EquipeCirurgicaCE() {

        initComponents();
        gec = GerenciaEquipeCirurgica.getInstance();
        fd = FuncionarioDao.getInstance();
        ecd = EquipeCirurgicaDao.getInstance();
        ecs = ecd.listarE();
        preencheCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tfCirculante = new javax.swing.JTextField();
        tfAnestesista = new javax.swing.JTextField();
        tfInstrumentador = new javax.swing.JTextField();
        tfEnfermeiroChefe = new javax.swing.JTextField();
        tfCirurgiaoPrincipal = new javax.swing.JTextField();
        tfCirurgiaoAssistente = new javax.swing.JTextField();
        btnAcao = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        cbxFuncionarios = new javax.swing.JComboBox<>();

        setClosable(true);

        tfCirculante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Circulante", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tfAnestesista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anestesista", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tfInstrumentador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instrumentador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tfEnfermeiroChefe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enfermeiro Chefe", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tfCirurgiaoPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cirurgião Principal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tfCirurgiaoAssistente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cirurgião Assistente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        tfCirurgiaoAssistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCirurgiaoAssistenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCirurgiaoAssistente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(tfCirurgiaoPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfEnfermeiroChefe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfInstrumentador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAnestesista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfCirculante, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tfCirculante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAnestesista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfInstrumentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEnfermeiroChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCirurgiaoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCirurgiaoAssistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        btnProximo.setText(">>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        cbxFuncionarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxFuncionariosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnAnterior)
                    .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void preencheCampos() {
        if (ecs == null || ecs.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum funcionario cadastrado!");
            btnAcao.setEnabled(false);
        } else {
            for (int i = 0; i < ecs.size(); i++) {
                cbxFuncionarios.addItem("Equipe id: " + ecs.get(i).getId());

            }

        }
    }

    public void Campos(int i) {

        {

            model.EquipeCirurgica equipeCirurgica = ecs.get(cbxFuncionarios.getSelectedIndex());
            tfAnestesista.setText(equipeCirurgica.getAnestesista().getNome() + " " + equipeCirurgica.getAnestesista().getSobrenome());

            tfCirculante.setText(equipeCirurgica.getCirculante().getNome() + " " + equipeCirurgica.getCirculante().getSobrenome());

            tfCirurgiaoAssistente.setText(equipeCirurgica.getCirurgiaoAssistente().getNome() + " " + equipeCirurgica.getCirurgiaoAssistente().getSobrenome());
            tfCirurgiaoPrincipal.setText(equipeCirurgica.getCirurgiaoPrincipal().getNome() + " " + equipeCirurgica.getCirurgiaoPrincipal().getSobrenome());

            tfEnfermeiroChefe.setText(equipeCirurgica.getEnfermeiroChefe().getNome() + " " + equipeCirurgica.getEnfermeiroChefe().getSobrenome());

            tfInstrumentador.setText(equipeCirurgica.getInstrumentador().getNome() + " " + equipeCirurgica.getInstrumentador().getSobrenome());

        }

    }


    private void cbxFuncionariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxFuncionariosItemStateChanged

        Campos(cbxFuncionarios.getSelectedIndex());
    }//GEN-LAST:event_cbxFuncionariosItemStateChanged

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (cbxFuncionarios.getItemCount() != 0) {

            if (cbxFuncionarios.getSelectedIndex() - 1 < 0) {
                cbxFuncionarios.setSelectedIndex(cbxFuncionarios.getItemCount() - 1);
            } else {

                cbxFuncionarios.setSelectedIndex(cbxFuncionarios.getSelectedIndex() - 1);
            }
        }    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed

        if (cbxFuncionarios.getItemCount() != 0) {

            if (cbxFuncionarios.getSelectedIndex() + 1 >= cbxFuncionarios.getItemCount()) {
                cbxFuncionarios.setSelectedIndex(0);
            } else {

                cbxFuncionarios.setSelectedIndex(cbxFuncionarios.getSelectedIndex() + 1);
            }
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void tfCirurgiaoAssistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCirurgiaoAssistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCirurgiaoAssistenteActionPerformed

    public abstract void btnAcaoActionPerformed(java.awt.event.ActionEvent evt);

    public GerenciaEquipeCirurgica getGec() {
        return gec;
    }

    public JComboBox<String> getCbxFuncionarios() {
        return cbxFuncionarios;
    }

    public ArrayList<EquipeCirurgica> getEcs() {
        return ecs;
    }

    public FuncionarioDao getFd() {
        return fd;
    }

    public JButton getBtnAcao() {
        return btnAcao;
    }

    public JTextField getTfAnestesista() {
        return tfAnestesista;
    }

    public JTextField getTfCirculante() {
        return tfCirculante;
    }

    public JTextField getTfCirurgiaoAssistente() {
        return tfCirurgiaoAssistente;
    }

    public JTextField getTfCirurgiaoPrincipal() {
        return tfCirurgiaoPrincipal;
    }

    public JTextField getTfEnfermeiroChefe() {
        return tfEnfermeiroChefe;
    }

    public JTextField getTfInstrumentador() {
        return tfInstrumentador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnProximo;
    private javax.swing.JComboBox<String> cbxFuncionarios;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfAnestesista;
    private javax.swing.JTextField tfCirculante;
    private javax.swing.JTextField tfCirurgiaoAssistente;
    private javax.swing.JTextField tfCirurgiaoPrincipal;
    private javax.swing.JTextField tfEnfermeiroChefe;
    private javax.swing.JTextField tfInstrumentador;
    // End of variables declaration//GEN-END:variables
}
