/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mae;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import model.Funcionario;

/**
 *
 * @author Wanderson_M
 */
public abstract class Pessoa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pessoa
     */
    private boolean CadastrouEndereco = false;
    protected javax.swing.JButton jbAcao;
    private String funcao, painel;

    public Pessoa(String painel, String funcao) {
        initComponents();
        visivel(painel);
        this.funcao = funcao;
        this.painel = painel;
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        JDesktop = new javax.swing.JDesktopPane();
        jtAvanco = new javax.swing.JTabbedPane();
        jpAvanco1 = new javax.swing.JPanel();
        jpCampos = new javax.swing.JPanel();
        jpPessoa = new javax.swing.JPanel();
        jftfDataNascimento = new javax.swing.JFormattedTextField();
        jftfTelefone = new javax.swing.JFormattedTextField();
        tfSobrenome = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jftfCpf = new javax.swing.JFormattedTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        jpPaciente = new javax.swing.JPanel();
        jlPeso = new javax.swing.JLabel();
        jsPeso = new javax.swing.JSpinner();
        jpFuncionario = new javax.swing.JPanel();
        ftfCtps = new javax.swing.JFormattedTextField();
        ftfRegistroProfissional = new javax.swing.JFormattedTextField();
        ftfDataInscricao = new javax.swing.JFormattedTextField();
        tfEspecialidade = new javax.swing.JTextField();
        tfFuncao = new javax.swing.JTextField();
        jbProximo = new javax.swing.JButton();
        jpAvanco2 = new javax.swing.JPanel();
        jpCampos1 = new javax.swing.JPanel();
        tfLogradouro = new javax.swing.JTextField();
        tfNumero = new javax.swing.JFormattedTextField();
        tfBairro = new javax.swing.JTextField();
        cbxUf = new javax.swing.JComboBox<>();
        tfComplemento = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JToggleButton();
        jftfCep = new javax.swing.JFormattedTextField();

        setClosable(true);
        getContentPane().setLayout(null);

        JDesktop.setBackground(new java.awt.Color(60, 63, 65));
        JDesktop.setForeground(new java.awt.Color(102, 102, 102));

        jtAvanco.setEnabled(false);

        jpCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCamposMouseClicked(evt);
            }
        });

        jftfDataNascimento.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Nascimento"));
        try {
            jftfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jftfTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));
        try {
            jftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tfSobrenome.setBorder(javax.swing.BorderFactory.createTitledBorder("Sobrenome"));

        tfNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        jftfCpf.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        try {
            jftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bgSexo.add(rbMasculino);
        rbMasculino.setText("Masculino");

        bgSexo.add(rbFeminino);
        rbFeminino.setText("Feminino");

        javax.swing.GroupLayout jpPessoaLayout = new javax.swing.GroupLayout(jpPessoa);
        jpPessoa.setLayout(jpPessoaLayout);
        jpPessoaLayout.setHorizontalGroup(
            jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPessoaLayout.createSequentialGroup()
                        .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPessoaLayout.createSequentialGroup()
                        .addComponent(jftfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(rbMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(rbFeminino))
                    .addGroup(jpPessoaLayout.createSequentialGroup()
                        .addComponent(tfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jpPessoaLayout.setVerticalGroup(
            jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPessoaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMasculino)
                    .addComponent(rbFeminino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlPeso.setText("Peso");

        jsPeso.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(1.0f), Float.valueOf(180.0f), Float.valueOf(1.0f)));

        javax.swing.GroupLayout jpPacienteLayout = new javax.swing.GroupLayout(jpPaciente);
        jpPaciente.setLayout(jpPacienteLayout);
        jpPacienteLayout.setHorizontalGroup(
            jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPacienteLayout.setVerticalGroup(
            jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPacienteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jpPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPeso)
                    .addComponent(jsPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ftfCtps.setBorder(javax.swing.BorderFactory.createTitledBorder("CTPS"));
        try {
            ftfCtps.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ftfRegistroProfissional.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Profissional"));
        try {
            ftfRegistroProfissional.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ftfDataInscricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Inscrição"));
        try {
            ftfDataInscricao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tfEspecialidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Especialidade"));

        tfFuncao.setEditable(false);
        tfFuncao.setBorder(javax.swing.BorderFactory.createTitledBorder("Função"));

        javax.swing.GroupLayout jpFuncionarioLayout = new javax.swing.GroupLayout(jpFuncionario);
        jpFuncionario.setLayout(jpFuncionarioLayout);
        jpFuncionarioLayout.setHorizontalGroup(
            jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFuncionarioLayout.createSequentialGroup()
                        .addComponent(ftfCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfDataInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfRegistroProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFuncionarioLayout.createSequentialGroup()
                        .addComponent(tfFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFuncionarioLayout.setVerticalGroup(
            jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfRegistroProfissional, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftfCtps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftfDataInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpCamposLayout = new javax.swing.GroupLayout(jpCampos);
        jpCampos.setLayout(jpCamposLayout);
        jpCamposLayout.setHorizontalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpCamposLayout.setVerticalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbProximo.setText("Proximo");
        jbProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAvanco1Layout = new javax.swing.GroupLayout(jpAvanco1);
        jpAvanco1.setLayout(jpAvanco1Layout);
        jpAvanco1Layout.setHorizontalGroup(
            jpAvanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAvanco1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpAvanco1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jbProximo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpAvanco1Layout.setVerticalGroup(
            jpAvanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAvanco1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbProximo)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jtAvanco.addTab("Cadastro Inicial", jpAvanco1);

        tfLogradouro.setBorder(javax.swing.BorderFactory.createTitledBorder("Logradouro"));

        tfNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("Número"));

        tfBairro.setBorder(javax.swing.BorderFactory.createTitledBorder("Bairro"));

        cbxUf.setMaximumRowCount(4);
        cbxUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MG", "RO", "AC", "AM", "RR", "PA", "AP", "TO", "MA", "PI", "CE", "RN", "PB", "PE", "AL", "SE", "BA", "ES", "RJ", "SP", "PR", "SC", "RS", "MS", "MT", "GO", "DF" }));
        cbxUf.setBorder(javax.swing.BorderFactory.createTitledBorder("UF"));

        tfComplemento.setBorder(javax.swing.BorderFactory.createTitledBorder("Complemento"));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnVoltarKeyReleased(evt);
            }
        });

        jftfCep.setBorder(javax.swing.BorderFactory.createTitledBorder("CEP"));
        try {
            jftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jpCampos1Layout = new javax.swing.GroupLayout(jpCampos1);
        jpCampos1.setLayout(jpCampos1Layout);
        jpCampos1Layout.setHorizontalGroup(
            jpCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCampos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCampos1Layout.createSequentialGroup()
                        .addComponent(cbxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftfCep))
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(tfComplemento))
                    .addComponent(btnVoltar))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpCampos1Layout.setVerticalGroup(
            jpCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCampos1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jpCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCampos1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tfComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                    .addGroup(jpCampos1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tfBairro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCampos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpAvanco2Layout = new javax.swing.GroupLayout(jpAvanco2);
        jpAvanco2.setLayout(jpAvanco2Layout);
        jpAvanco2Layout.setHorizontalGroup(
            jpAvanco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAvanco2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCampos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jpAvanco2Layout.setVerticalGroup(
            jpAvanco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAvanco2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCampos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jtAvanco.addTab("Endereço", jpAvanco2);

        JDesktop.setLayer(jtAvanco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JDesktopLayout = new javax.swing.GroupLayout(JDesktop);
        JDesktop.setLayout(JDesktopLayout);
        JDesktopLayout.setHorizontalGroup(
            JDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtAvanco, javax.swing.GroupLayout.PREFERRED_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        JDesktopLayout.setVerticalGroup(
            JDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtAvanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(JDesktop);
        JDesktop.setBounds(0, 6, 458, 488);
        JDesktop.getAccessibleContext().setAccessibleParent(JDesktop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private  void jpCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCamposMouseClicked
        int x, y;
        x = evt.getX();
        y = evt.getY();


    }//GEN-LAST:event_jpCamposMouseClicked

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
        jtAvanco.setSelectedIndex(1);

    }//GEN-LAST:event_jbProximoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        jtAvanco.setSelectedIndex(0);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVoltarKeyReleased

        System.out.println( "X: " +btnVoltar.getX()+ "Y: "+btnVoltar.getY());

    }//GEN-LAST:event_btnVoltarKeyReleased

    public void visivel(String painel) {

        if (painel.equals("paciente")) {
            this.setSize(435, 400);
            jpCampos.add(jbProximo);
            jbProximo.setBounds(100, 100, 80, 25);
            jpPaciente.setVisible(true);
            jpFuncionario.setVisible(false);
        } else if (painel.equals("funcionario")) {
            jpFuncionario.setVisible(true);
            jpPaciente.setVisible(false);
            this.setSize(435, 550);

        }
    }

    public void SalvarBotoes() {
        jpCampos1.add(jbAcao);
        jbAcao.setBounds(220, 190, 80, 30);

    }

    public JFormattedTextField getFtfCtps() {
        return ftfCtps;
    }

    public JFormattedTextField getFtfDataInscricao() {
        return ftfDataInscricao;
    }

    public JFormattedTextField getFtfRegistroProfissional() {
        return ftfRegistroProfissional;
    }

    public JFormattedTextField getJftfCpf() {
        return jftfCpf;
    }

    public JFormattedTextField getJftfDataNascimento() {
        return jftfDataNascimento;
    }

    public JFormattedTextField getJftfTelefone() {
        return jftfTelefone;
    }

    public JTextField getTfEspecialidade() {
        return tfEspecialidade;
    }

    public JTextField getTfFuncao() {
        return tfFuncao;
    }

    public JTextField getTfNome() {
        return tfNome;
    }

    public JTextField getTfSobrenome() {
        return tfSobrenome;
    }

    public JSpinner getJsPeso() {
        return jsPeso;
    }

    public JDesktopPane getJDesktop() {
        return JDesktop;
    }

    public JComboBox<String> getCbxUf() {
        return cbxUf;
    }

    public JTextField getTfBairro() {
        return tfBairro;
    }

    public JTextField getTfComplemento() {
        return tfComplemento;
    }

    public JTextField getTfLogradouro() {
        return tfLogradouro;
    }

    public JFormattedTextField getTfNumero() {
        return tfNumero;
    }

    public ButtonGroup getBgSexo() {
        return bgSexo;
    }

    public JFormattedTextField getJftfCep() {
        return jftfCep;

    }

    

    public JRadioButton getRbFeminino() {
        return rbFeminino;
    }

    public JRadioButton getRbMasculino() {
        return rbMasculino;
    }

    public abstract void jbAcaoActionPerformed(java.awt.event.ActionEvent evt, String painel);

    public void instanciaBotaoAcao(String titulo) {
        jbAcao = new JButton();
        jbAcao.setText(titulo);
        jbAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcaoActionPerformed(evt, painel);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JDesktopPane JDesktop;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JComboBox<String> cbxUf;
    private javax.swing.JFormattedTextField ftfCtps;
    private javax.swing.JFormattedTextField ftfDataInscricao;
    private javax.swing.JFormattedTextField ftfRegistroProfissional;
    private javax.swing.JButton jbProximo;
    private javax.swing.JFormattedTextField jftfCep;
    private javax.swing.JFormattedTextField jftfCpf;
    private javax.swing.JFormattedTextField jftfDataNascimento;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JLabel jlPeso;
    private javax.swing.JPanel jpAvanco1;
    private javax.swing.JPanel jpAvanco2;
    protected javax.swing.JPanel jpCampos;
    private javax.swing.JPanel jpCampos1;
    private javax.swing.JPanel jpFuncionario;
    private javax.swing.JPanel jpPaciente;
    private javax.swing.JPanel jpPessoa;
    private javax.swing.JSpinner jsPeso;
    private javax.swing.JTabbedPane jtAvanco;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfEspecialidade;
    private javax.swing.JTextField tfFuncao;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfNumero;
    private javax.swing.JTextField tfSobrenome;
    // End of variables declaration//GEN-END:variables
}
